/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prac2.sdpt2;


import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class App {

    public static void main(String[] args) {

        String filePath = "../app/files/data.xml";

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;

            // Read each line in the file
            while ((line = br.readLine()) != null) {
                // Split the line by comma
                String[] fields = line.split(",");

                // Print the field values
                for (String field : fields) {
                    System.out.print(field.trim() + " ");
                }
                System.out.println();
            }

        } catch (IOException e) {
            System.err.format("IOException: %s%n", e);
        }
    }
}
