/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prac2.sdpt2;


import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        //Creating a scanner object
        Scanner sc =  new Scanner(System.in);
        System.out.println("Enter the field names (comma-separated):");

        // Input file and selected fields
        File inputFile = new File("../app/files/data.xml");
        List<String> selectedFields = new ArrayList<>();
        String fieldNamesInput = sc.nextLine();
        selectedFields.add(fieldNamesInput);
        

        // Create a SAX parser factory and configure it
        SAXParserFactory saxParserFactory = SAXParserFactory.newInstance();
        saxParserFactory.setValidating(false);
        saxParserFactory.setNamespaceAware(false);

        try {
            // Create a SAX parser and define a handler for parsing events
            SAXParser saxParser = saxParserFactory.newSAXParser();
            DefaultHandler handler = new DefaultHandler() {
                boolean inSelectedField = false;

                public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException {
                    // Check if the element is one of the selected fields
                    if (selectedFields.contains(qName)) {
                        inSelectedField = true;
                    }
                }

                public void characters(char ch[], int start, int length) throws SAXException {
                    // Output the element value if it is one of the selected fields
                    if (inSelectedField) {
                        System.out.println(new String(ch, start, length));
                        inSelectedField = false;
                    }
                }
            };

            // Parse the XML file and trigger the handler for parsing events
            saxParser.parse(inputFile, handler);
        } catch (ParserConfigurationException | SAXException | IOException e) {
            e.printStackTrace();
        }
    }
}
